### PR TITLE
Remove unnecessary templating.

### PR DESCRIPTION
**Pull request by awoods**

### CODE REVIEW

**Comment by bbpennel** [comment]
I am okay with this approach if others prefer it, the reason for all the generics was to make the API easier to extend.  For instance, in this pull request, if you call client.post(uri).body(inputstream) it returns a BodyRequestObject instead of a PostRequest, and you would not have access to post specific methods like digest.  

You can get around that by adding overrides for every API method (which you started on), which is more duplication when extending.  So it's just a trade off, and the initial discussion with @ajs6f on the ticket went the other way.  But I do find this approach much more readable.

**Comment by ajs6f** [comment]
It is more readable, but that's only because the API isn't complete (to my mind). Until there is a single starting point (and not a bunch of constructors) the utility of the generics isn't visible.

**Comment by awoods** [comment]
How much more extension do you have in mind? It seems like you have already implemented the HTTP methods in this PR. I would suggest polymorphism over this sort of templating.

**Comment by ajs6f** [comment]
Even before extension, polymorphism fails to provide true factory methods instead of constructors.

**Comment by bbpennel** [comment]
I'm not sure which way to go with this.  After playing around with andrews branch some I haven't noticed major issues.  There are other API end points that I think should be added to this client in the future, namely transaction creation, versioning, etc, but they would not benefit from extending existing implementations.  Use cases for extending this client aren't readily coming to mind, but that may just be a failure of imagination on my part.

**Comment by ajs6f** [comment]
Have you provided the single-method starting pöint? If so, I wouldn't worry too much about the rest, myself.

**Comment by bbpennel** [comment]
``` java
FcrepoResponse response = FcrepoClient
    .withAuthentication(user, pass, host)
    .throwExceptionOnFailure()
    .create() // Returns FcrepoClient
    .post(uri) // Returns PostBuilder
    .withBody(body, type)
    .perform();
```

does this seem like what you have in mind?  Or starting with FcrepoClient.create

**Comment by ajs6f** [comment]
More or less. (I would break `host` out of `withAuthentication`.)

**Comment by ajs6f** [comment]
There's another conversation to be had here about whether a client that offers methods like `post` and `put` is actually high-level enough to be a valuable artifact, but that's a separate conversation.

**Comment by bbpennel** [comment]
host is the authentication scope host, so I'll make sure it has a more sensible variable name but keep it in withAuthentication, and make it optional.

I agree that having methods like `post` is not very user friendly in terms of indicating what the purpose of the operation is.  We could rename the starting method names based on purpose rather than http method, which would mainly mean splitting PUT into two starting methods.

**Pull request merged**
